version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexicon-bo-test
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=testing
      - DB_USERNAME=testing
      - DB_PASSWORD=testing
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_STORE=array
      - SESSION_DRIVER=array
      - QUEUE_CONNECTION=sync
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - test-network

  postgres:
    image: postgres:16-alpine
    container_name: lexicon-bo-test-postgres
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testing -d testing"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lexicon-bo-test-redis
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  test-network:
    driver: bridge
